### ISSUE TITLE
as_html cannot find module

### ISSUE THREAD

**Issue by zachvalenta** [timothycrosley/pdocs#3]
Messing around with the CLI and running into a problem when I try to build docs as HTML.

```
(venv) $ l
.rw-r--r--@   14 zach  5 Sep  8:41 -- .gitignore
.rw-r--r--   135 zach  5 Sep  8:41 -- app.py
.rw-r--r--@  187 zach  5 Sep  8:41 -- Dockerfile
.rw-r--r--@ 1.1k zach  5 Sep  8:41 -- LICENSE
.rw-r--r--  1.4k zach  5 Sep  8:41 -- Makefile
.rw-r--r--@  974 zach  5 Sep  8:41 -- README.md
.rw-r--r--    94 zach  5 Sep  8:41 -- requirements.txt

(venv) $ pdocs as_html  # operator error
Please provide one or more modules

(venv) $ pdocs as_html app.py  # expected this to work though
Module not found: app.py
```

**Comment by michaeljoseph** [comment]
@zachvalenta i _think_ the module would be `app` in your example?

**Comment by timothycrosley** [comment]
Closing this as @michaeljoseph is correct. @zachvalenta I hope you were able to resolve your issue and if it's still around please feel empowered to create a new issue.

Thanks!

~Timothy

**Comment by zachvalenta** [comment]
Sorry for the lag with this. I get the error `module not found` for both `pdocs as_html app.py` and `pdocs as_html app`.
