### ISSUE TITLE
Numpydoc support

### ISSUE THREAD

**Issue by mivade** [timothycrosley/pdocs#4]
It would be great if this could support [numpy-style docstrings][numpydoc] as this format is widely used in scientific computing applications.

[numpydoc]: https://numpydoc.readthedocs.io/en/latest/format.html

**Comment by PanRe** [comment]
That would be awesome! I would need that feature too!

**Comment by tlambert03** [comment]
+1 ... outside of that: pdocs is 🤩!

**Comment by sanzoghenzo** [comment]
It would be great to also support [Google style docstrings](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).

I'm adding it to this issue instead of adding a new one because of `sphinxcontrib-napoleon` , that does it well for reST.

**Comment by kylebarron** [comment]
I took a quick look... It looks like docstrings are generally parsed and stored on the `Doc` object here:
https://github.com/timothycrosley/pdocs/blob/6284c6abd5c2eb2f4aa458b0f6d6cbb7fd39b640/pdocs/doc.py#L145-L149

I was thinking that you could use something like https://github.com/rr-/docstring_parser to parse that string; it appears to work with several different types of docstrings. `docstring_parser.parse` outputs an object with attributes representing the parts of the parsed docstring. E.g.:

```py
from docstring_parser import parse

docstring = parse(
    '''
    Attributes
    ----------
    filepath: str
        Cloud Optimized GeoTIFF path.
    ''')

docstring.params[0].default
# None
docstring.params[0].arg_name
# 'filepath'
docstring.params[0].type_name
# 'str'
docstring.params[0].is_optional
# False
docstring.params[0].description
# 'Cloud Optimized GeoTIFF path.'
```

My thinking was that you could pass this parsed docstring object down to the Mako template, and loop over the values there. I tried it out but the internals are pretty complex to me and [my branch](https://github.com/kylebarron/pdocs/tree/parse-docstring) isn't functional. Any suggestions?

**Comment by sanzoghenzo** [comment]
I also took a look at it a month ago, and I saw that the docstring is taken as is and passed to the "plain text"/markdown output or mako for html output.

So the fastest way to do this without touching too much of the existing code would be to write a Google/numpydocs to markdown converter that can be chained with `cleandoc`.

This is what Napoleon does for ReStructuredText. In fact, I was going to copy its parsers and change the ReST part with markdown, but higher priority tasks came up.

The downside to this is that you lose the structure of the docstring, an you can't combine, for example, the parameters with the type annotation in the signature.

**Comment by kylebarron** [comment]
> So the fastest way to do this without touching too much of the existing code would be to write a Google/numpydocs to markdown converter that can be chained with `cleandoc`.

I agree this is "fastest", but I think you'll lose a lot of flexibility by -- in effect -- pre-rendering the docstring with a hardcoded docstring-to-markdown converter. It seems preferable to expose the parts of the docstring directly to the Mako template, as then users can customize exactly how they want their docstring to look.

What I was trying to do on my branch was to use `docstring-parser` to provide a docstring _object_ to the Mako template, where the `text` attribute contains the docstring as text for users who write their docstrings in Markdown or don't want to use the full flexibility; otherwise use the parsed parts of the docstring for better rendering.

**Comment by sanzoghenzo** [comment]
> [...] I think you'll lose a lot of flexibility by -- in effect -- pre-rendering the docstring with a hardcoded docstring-to-markdown converter. It seems preferable to expose the parts of the docstring directly to the Mako template, as then users can customize exactly how they want their docstring to look.
>
> What I was trying to do on my branch was to use `docstring-parser` to provide a docstring _object_ to the Mako template, where the `text` attribute contains the docstring as text for users who write their docstrings in Markdown or don't want to use the full flexibility; otherwise use the parsed parts of the docstring for better rendering.

You're totally right.
I'm interested in is the compatibility with portray, that uses the `pdocs.api.as_markdown` method to gather the markdown of the API reference, and in my previous analysis I wrongly assumed that I needed to have the docstring as an already rendered markdown;
But as you said, we can pass an object to the Mako templates (both for html and markdown output), and handle the rendering directly there.

I took a look at your code, and I suggest to:

- keep the original `docstring` as string for retrocompatibility (and to avoid changing all the code with `docstring.text`);
- save the output of the `docstring_parser.parse` in the `parsed_docstring` attribute, catching ParseError (this will get rid of the parse_docstring function):

```python
try:
    self.parsed_docsting = docstring_parser.parse(self.docstring)
except ParseError:
    self.parsed_docsting = None
```

- in the templates you can check for `parsed_docstring` truthiness and build the markdown/html, or fall back to `docstring`:

```mako
% if func.parsed_docstring:
    # table with arguments info
    % if func.parsed_docstring.params:
| Parameter | type | description | default |
|---|---|---|---|
        % for p in func.parsed_docstring.params:
| ${p.arg_name} | ${p.type_name} | ${p.description} | ${p.default} |
    % endif
% else
${func.docstring}
% endif
```

**Comment by kylebarron** [comment]
Yeah those are great ideas. I'll see if I can try it out tonight. Mostly I just haven't worked with Mako before so I'm not used to working with those templates
